/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <linux/fs.h>
#include <linux/fs_context.h>

// struct hayleyfs_mount_opts {
//   bool init;
// };

struct hayleyfs_mount_opts {
  bool init;
};

struct hayleyfs_fs_info {
  struct hayleyfs_mount_opts mount_opts;
};

// struct fs_context_operations {
//   uint8_t _unused[0];
// };

int hayleyfs_fill_super(struct super_block *sb, struct fs_context *fc);

// extern void hayleyfs_fs_context_set_fs_info(fs_context *fc, const struct hayleyfs_fs_info *info);

// extern void hayleyfs_fs_context_set_ops(fs_context *fc, const struct fs_context_operations *ops);

// extern int32_t hayleyfs_get_tree(fs_context *fc);

int hayleyfs_get_tree_rust(struct fs_context *fc);

// int hayleyfs_init_fs_context(fs_context *fc);

// void hayleyfs_put_super(super_block *sb);

// int init_hayleyfs(void);
