/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <linux/fs.h>
#include <linux/fs_context.h>

struct hayleyfs_mount_opts {
  bool init;
};

struct hayleyfs_fs_info {
  struct hayleyfs_mount_opts mount_opts;
};

int hayleyfs_fill_super(struct super_block *sb, struct fs_context *fc);

int hayleyfs_get_tree_rust(struct fs_context *fc);

