/*
 * Resizable simple ram filesystem for Linux.
 *
 * Copyright (C) 2000 Linus Torvalds.
 *               2000 Transmeta Corp.
 *
 * Usage limits added by David Gibson, Linuxcare Australia.
 * This file is released under the GPL.
 */

/*
 * NOTE! This filesystem is probably most useful
 * not as a real filesystem, but as an example of
 * how virtual filesystems can be written.
 *
 * It doesn't get much simpler than this. Consider
 * that this file implements the full semantics of
 * a POSIX-compliant read-write filesystem.
 *
 * Note in particular how the filesystem does not
 * need to implement any data structures of its own
 * to keep track of the virtual data: using the VFS
 * caches is sufficient.
 */

#include <linux/fs.h>
#include <linux/pagemap.h>
#include <linux/highmem.h>
#include <linux/time.h>
#include <linux/init.h>
#include <linux/string.h>
#include <linux/backing-dev.h>
#include <linux/ramfs.h>
#include <linux/sched.h>
#include <linux/parser.h>
#include <linux/magic.h>
#include <linux/slab.h>
#include <linux/uaccess.h>
#include <linux/fs_context.h>
#include <linux/fs_parser.h>
#include "internal.h"
#include "inode_rs.h"

#define RAMFS_DEFAULT_MODE	0755

void ramfs_mapping_set_gfp_mask(struct address_space *m, gfp_t mask)
{
	mapping_set_gfp_mask(m, mask);
}

void ramfs_mapping_set_unevictable(struct address_space *mapping)
{
	mapping_set_unevictable(mapping);
}

gfp_t ramfs_get_gfp_highuser(void)
{
  return GFP_HIGHUSER;
}

/* Necessary b/c dget is an inline only method that we need a symbol
   access to in Rust. I read about the providing method for inlines in
   this article https://lwn.net/Articles/829858/*/
struct dentry *ramfs_rust_dget(struct dentry *dentry)
{
	return dget(dentry);
}

/* proper way of handling static functions is probably
  (like linux) to manually read the
  elf symbol table, but we just remove static for development purposes
  - once finished - will not matter */

/* Necessary b/c fs_parse is an inline method that we need a symbol
   access to in Rust. I read about the providing method for inlines in
   this article https://lwn.net/Articles/829858/*/
int rust_fs_parse(struct fs_context *fc,
		  const struct fs_parameter_spec *desc,
		  struct fs_parameter *param,
		  struct fs_parse_result *result)
{
	return fs_parse(fc, desc, param, result);
}

loff_t ramfs_get_max_lfs_filesize(void)
{
	return MAX_LFS_FILESIZE;
}

unsigned long ramfs_get_page_size(void)
{
	return PAGE_SIZE;
}

unsigned char ramfs_get_page_shift(void)
{
	return PAGE_SHIFT;
}

unsigned long ramfs_get_ramfs_magic(void)
{
	return RAMFS_MAGIC;
}

int ramfs_rust_get_tree_nodev(struct fs_context* fc,
            int (*fill_super)(struct super_block *sb, struct fs_context *fc))
{
    return get_tree_nodev(fc, fill_super);
}

// cannot convert until we generate more bindings
const struct fs_context_operations ramfs_context_ops = {
	.free		= ramfs_free_fc,
	.parse_param	= ramfs_parse_param,
	.get_tree	= ramfs_get_tree,
};

/*
 * Necessary b/c fs_context seems to be an opaque type in bindings
 * generated by bindgen. Not sure why this is.
 *
 * Split into two functions to keep logic in rust and make refactoring easier
 * in the future.
 */
void ramfs_rust_fs_context_set_ops(struct fs_context *fc,
				   const struct fs_context_operations *ops)
{
	fc->ops = ops;
}

/*
 * Necessary b/c fs_context seems to be an opaque type in bindings
 * generated by bindgen. Not sure why this is.
 */
struct ramfs_fs_info *ramfs_rust_fs_context_get_s_fs_info(struct fs_context *fc)
{
	return fc->s_fs_info;
}

/*
 * Necessary b/c fs_context seems to be an opaque type in bindings
 * generated by bindgen. Not sure why this is.
 */
void ramfs_rust_fs_context_set_s_fs_info(struct fs_context *fc,
					 struct ramfs_fs_info *fsi)
{
	fc->s_fs_info = fsi;
}

fs_initcall(init_ramfs_fs);